### PR TITLE
Test for user service impl   confirm user registration

### LINKED ISSUE #101: Test for UserServiceImpl - confirmUserRegistration
Tests for the confirmUserRegistration method:

- [ ] Verify that the method successfully confirms user registration based on a valid token.
- [ ] Verify that the method throws an exception when the provided token does not exist.
- [ ] Verify that the method throws an exception when the provided token is not of the registration confirmation type.
- [ ] Verify that the method throws an exception when the token has already been confirmed.
- [ ] Verify that the method throws an exception when the user is already enabled.

_**instructions for the task**_
_use the convention //given //when //then
mock all injected dependencies with business logic using the Mockito library, e.g. UserRepository
try to use the BDD methodology, e.g. the assertJ library (optional)

### PR DESCRIPTION
**Pull request by GrzegorzHolui**

### CODE REVIEW

**Comment by McBlankenburg** [comment]
image
Repair this bug

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 1]
```diff
@@ -37,6 +49,14 @@ class UserServiceImplTest {
     @InjectMocks
     private UserServiceImpl userServiceImpl;
 
+    @Mock
+    PasswordEncoder passwordEncoder;
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: private

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 2]
```diff
@@ -37,6 +49,14 @@ class UserServiceImplTest {
...
+    @Mock
+    JavaMailSender mailSender;
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: private

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 3]
```diff
@@ -37,6 +49,14 @@ class UserServiceImplTest {
...
+    @Spy
+    UserModelMapper userModelMapper;
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: private

File: src/main/java/pl/simpleascoding/tutoringplatform/user/UserServiceImpl.java [hunk 4]
```diff
@@ -9,14 +9,12 @@
 import org.springframework.security.crypto.password.PasswordEncoder;
 import org.springframework.stereotype.Service;
 import org.springframework.transaction.annotation.Transactional;
-import pl.simpleascoding.tutoringplatform.util.rscp.RscpDTO;
+import pl.simpleascoding.tutoringplatform.security.jwt.Token;
+import pl.simpleascoding.tutoringplatform.security.jwt.TokenRepository;
```
Comment (McBlankenburg) [inline src/main/java/pl/simpleascoding/tutoringplatform/user/UserServiceImpl.java:13]: useless import

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 5]
```diff
@@ -5,16 +5,28 @@
...
 
+import java.time.LocalDateTime;
 import java.util.Optional;
 
 import static org.hamcrest.MatcherAssert.assertThat;
 import static org.hamcrest.Matchers.equalTo;
 import static org.hamcrest.Matchers.is;
 import static org.junit.jupiter.api.Assertions.assertThrows;
-import static org.mockito.Mockito.when;
+import static org.mockito.BDDMockito.given;
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java:27]: useless import

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java (hunk 1 above)
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: lack of import

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java (hunk 2 above)
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: lack of import

**Review by McBlankenburg — CHANGES_REQUESTED** [review]
the application does not build, deficiencies in imports, encapsulation of variables needs to be improved.

**Comment by MateuszCiapala** [comment]
In addition to that what @McBlankenburg said,
-remove unnecessary blank lines inside methods
-@DisplayName annotations should give short desc for eg. what method we're testing like: @DisplayName("confirmUserRegistration"), currently it's similar to the long method name which already describes what it is testing .)
-Consider extracting help methods like createUserEntity, createTokenEntity to helper class to avoid test classes being too long ( hundreds of lines of code for single test class may be considered as antypattern )

I'll review rest when it'll be finished and working (gh build has to pass)

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 6]
```diff
@@ -107,37 +88,36 @@ void whenGetUserByUsername_thenUserNotFoundExceptionShouldBeThrown() {
...
     void whenConfirmUserRegistration_thenUserRegistrationConfirmedShouldBeReturned() {
         //given
         Token tokenEntity = createTokenEntity();
 
         when(tokenRepository.findTokenByValue(tokenEntity.getValue())).thenReturn(Optional.of(tokenEntity));
         //when
-        RscpDTO<?> resultRscpDTO = userService.confirmUserRegistration(tokenEntity.getValue());
+        RscpDTO<?> resultRscpDTO = userServiceImpl.confirmUserRegistration(tokenEntity.getValue());
 
         RscpDTO<Object> expectedRscpDTO = new RscpDTO<>(RscpStatus.OK, "User registration confirmed.", null);
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: //when

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 7]
```diff
@@ -107,37 +88,36 @@ void whenGetUserByUsername_thenUserNotFoundExceptionShouldBeThrown() {
...
 
         assertThat(resultRscpDTO, is(equalTo(expectedRscpDTO)));
     }
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java:152]: I would add Mockito.verify() as static in short form just in case verify(), a method verifying whether tokenRepository was called once

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 8]
```diff
@@ -107,37 +88,36 @@ void whenGetUserByUsername_thenUserNotFoundExceptionShouldBeThrown() {
...
         Token tokenEntity = createTokenEntity();
 
         when(tokenRepository.findTokenByValue(tokenEntity.getValue())).thenReturn(Optional.of(tokenEntity));
         //when
-        RscpDTO<?> resultRscpDTO = userService.confirmUserRegistration(tokenEntity.getValue());
+        RscpDTO<?> resultRscpDTO = userServiceImpl.confirmUserRegistration(tokenEntity.getValue());
 
         RscpDTO<Object> expectedRscpDTO = new RscpDTO<>(RscpStatus.OK, "User registration confirmed.", null);
 
         assertThat(resultRscpDTO, is(equalTo(expectedRscpDTO)));
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java:151]: I would add in //then Mockito.verify() as static in short form just in case verify(), a method verifying whether tokenRepository was called once

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 9]
```diff
@@ -107,37 +88,36 @@ void whenGetUserByUsername_thenUserNotFoundExceptionShouldBeThrown() {
...
     void whenConfirmUserRegistration_thenUserRegistrationConfirmedShouldBeReturned() {
         //given
         Token tokenEntity = createTokenEntity();
 
         when(tokenRepository.findTokenByValue(tokenEntity.getValue())).thenReturn(Optional.of(tokenEntity));
         //when
-        RscpDTO<?> resultRscpDTO = userService.confirmUserRegistration(tokenEntity.getValue());
+        RscpDTO<?> resultRscpDTO = userServiceImpl.confirmUserRegistration(tokenEntity.getValue());
 
         RscpDTO<Object> expectedRscpDTO = new RscpDTO<>(RscpStatus.OK, "User registration confirmed.", null);
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: expectedRscpDTO should be in section //given

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 10]
```diff
@@ -107,37 +88,36 @@ void whenGetUserByUsername_thenUserNotFoundExceptionShouldBeThrown() {
         assertThrows(UserNotFoundException.class, () -> userServiceImpl.getUserByUsername(USERNAME));
     }
 
-    @DisplayName("Should return null and User registration confirmed.")
+    @DisplayName("confirmUserRegistration")
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: @DisplayName("should return expectedRscpDTO")  (i am not sure)

**Review by McBlankenburg — CHANGES_REQUESTED** [review]

**Comment by MateuszCiapala** [comment]
Branch is currently diverged with develop, it's required to be rebased. Consider of using "git reset --soft HEAD~X" where X is number of commits to be cancelled(you should verify the last common commit for you branch and develop and return to it), your changes will be moved back to staging area and you'll be able to commit them again. This is one of the simplest option to fix your issue, then you'll just need to force push to rewrite your remote feature branch history. Note that creating backup branch before such operations is a must !

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 11]
```diff
@@ -23,7 +23,7 @@
 import static org.hamcrest.Matchers.equalTo;
 import static org.hamcrest.Matchers.is;
 import static org.junit.jupiter.api.Assertions.assertThrows;
-import static org.mockito.Mockito.when;
+import static org.mockito.Mockito.*;
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: always use single imports for import reasons, you can set it in InteliJ to do it automatically

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 12]
```diff
@@ -93,13 +93,14 @@ void whenGetUserByUsername_thenUserNotFoundExceptionShouldBeThrown() {
...
         //given
         Token tokenEntity = createTokenEntity();
+        RscpDTO<Object> expectedRscpDTO = new RscpDTO<>(RscpStatus.OK, "User registration confirmed.", null);
 
-        when(tokenRepository.findTokenByValue(tokenEntity.getValue())).thenReturn(Optional.of(tokenEntity));
         //when
-        RscpDTO<?> resultRscpDTO = userServiceImpl.confirmUserRegistration(tokenEntity.getValue());
-
-        RscpDTO<Object> expectedRscpDTO = new RscpDTO<>(RscpStatus.OK, "User registration confirmed.", null);
+        when(tokenRepository.findTokenByValue(tokenEntity.getValue())).thenReturn(Optional.of(tokenEntity));
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: I recommend sticking to the Given When Then (BDD) convention

change Mockito.when() --> BDD Mockito given() (in //given section)
change Mockito.thenReturn() --> BDD Mockito .willReturn()
(of course without Mockito because we have static)

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 13]
```diff
@@ -93,13 +93,14 @@ void whenGetUserByUsername_thenUserNotFoundExceptionShouldBeThrown() {
...
 
+        //then
+        RscpDTO<?> resultRscpDTO = userServiceImpl.confirmUserRegistration(tokenEntity.getValue());
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: .confirmUserRegistration (we testing that method, so it should be in //when section)

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 14]
```diff
@@ -93,13 +93,14 @@ void whenGetUserByUsername_thenUserNotFoundExceptionShouldBeThrown() {
...
+        verify(tokenRepository, atLeastOnce()).findTokenByValue(tokenEntity.getValue());
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: atLeastOnce()   so it will be fine when we refactor method and we call repository 10 000x ? Is there a justification?

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 15]
```diff
@@ -108,12 +109,15 @@ void whenConfirmUserRegistration_thenUserRegistrationConfirmedShouldBeReturned()
     void whenConfirmUserRegistration_thenTokenNotFoundExceptionShouldBeThrown() {
         //given
         Token tokenEntity = createTokenEntity();
-        //when & then
+
+        //when
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java:161]: as above replace when() with given() and put it in //given section

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 16]
```diff
@@ -108,12 +109,15 @@ void whenConfirmUserRegistration_thenUserRegistrationConfirmedShouldBeReturned()
...
         when(tokenRepository.findTokenByValue(tokenEntity.getValue())).thenReturn(Optional.empty());
 
         TokenNotFoundException exception = assertThrows(TokenNotFoundException.class,
                 () -> userServiceImpl.confirmUserRegistration(tokenEntity.getValue()));
 
+        //then
+        verify(tokenRepository, atLeastOnce()).findTokenByValue(tokenEntity.getValue());
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: as above atLeastOnce() can i call it 10 000x ? Unit test it documentation for Software Developer, so when i read atLeastOnce it mean 1 or more.

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 17]
```diff
@@ -123,12 +127,14 @@ void whenConfirmUserRegistration_thenInvalidTokenExceptionShouldBeThrown() {
         //given
         Token tokenEntity = createTokenEntity();
         tokenEntity.setType(null);
-        //when & then
+
+        //when
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java:178]: Mockito.when() --> BDDMockito.given() as above

when() --> given()

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 18]
```diff
@@ -123,12 +127,14 @@ void whenConfirmUserRegistration_thenInvalidTokenExceptionShouldBeThrown() {
...
         when(tokenRepository.findTokenByValue(tokenEntity.getValue())).thenReturn(Optional.of(tokenEntity));
 
         InvalidTokenException exception = assertThrows(InvalidTokenException.class,
                 () -> userServiceImpl.confirmUserRegistration(tokenEntity.getValue()));
-
+        //then
+        verify(tokenRepository, atLeastOnce()).findTokenByValue(tokenEntity.getValue());
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: verify should be in //then section

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 19]
```diff
@@ -139,12 +145,13 @@ void whenConfirmUserRegistration_thenTokenAlreadyConfirmedExceptionShouldBeThrow
         Token tokenEntity = createTokenEntity();
         tokenEntity.setConfirmedAt(LocalDateTime.of(1, 1, 1, 1, 1));
 
-        //when & then
+        //when
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java:195]: as above

File: src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java [hunk 20]
```diff
@@ -154,12 +161,14 @@ void whenConfirmUserRegistration_thenUserAlreadyEnabledExceptionShouldBeThrown()
         //given
         Token tokenEntity = createTokenEntity();
         tokenEntity.getUser().setEnabled(true);
-        //when & then
-        when(tokenRepository.findTokenByValue(tokenEntity.getValue())).thenReturn(Optional.of(tokenEntity));
 
+        //when
+        when(tokenRepository.findTokenByValue(tokenEntity.getValue())).thenReturn(Optional.of(tokenEntity));
```
Comment (McBlankenburg) [inline src/test/java/pl/simpleascoding/tutoringplatform/user/UserServiceImplTest.java]: as above

**Review by McBlankenburg — CHANGES_REQUESTED** [review]

**Review by dawciobiel — APPROVED** [review]
LGTM,
next time please commit exactly only files that belong to this issue / pull-request

**Review by wh15tl3r — APPROVED** [review]
LGTM

**Review by McBlankenburg — APPROVED** [review]
good job
